# Generated by Django 3.0.4 on 2020-03-30 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200329_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllogin',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Membro da equipe'),
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id_incidents', models.AutoField(primary_key=True, serialize=False)),
                ('title_incident', models.CharField(max_length=100, verbose_name='Caso')),
                ('description_incident', models.TextField(verbose_name='Descrição')),
                ('value_incident', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor em Reais')),
                ('ong_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ong_incident',
                'managed': True,
            },
        ),
    ]
