# Generated by Django 3.0.4 on 2020-03-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200329_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllogin',
            name='ong',
        ),
        migrations.AlterField(
            model_name='controllogin',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Usuário'),
        ),
    ]
